package Amazon;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Interface extends javax.swing.JFrame {
    JList list;
    int currentBook = 0;
    int currentSoftware = 0;
    Book[] bookList;
    Software[] softwareList;
    
    DefaultListModel dlmBook = new DefaultListModel();
    DefaultListModel dlmSoftware = new DefaultListModel();
    DefaultListModel dlmOrder = new DefaultListModel();
    /**
     * Creates new form Interface
     */
    
    public Interface() {
        this.bookList = new Book [100];
        this.softwareList = new Software [100];
        
        initComponents();
        
        //Products p1 = new Products(1,"Microsoft Office",99.99,2014,"Microsoft");
        //Book b1 = new Book(1,"Microsoft Office",99.99,2014,"Microsoft","Eliazer Raizel", "123123DEASD123", 365);
        //Software s1 = new Software(1,"Microsoft Office",99.99,2014,"Microsoft",500, 2.2, "Windows 7");
        
        jBSubmit.setVisible(false);
        jLID.setVisible(false);
        jTID.setVisible(false);
        jLName.setVisible(false);
        jTName.setVisible(false);
        jLPHouse.setVisible(false);
        jTPHouse.setVisible(false);
        jLPYear.setVisible(false);
        jTPYear.setVisible(false);
        jLCost.setVisible(false);
        jTCost.setVisible(false);
        jLAuthor.setVisible(false);
        jTAuthor.setVisible(false);
        jLNPages.setVisible(false);
        jTNPages.setVisible(false);
        jLISBN.setVisible(false);
        jTISBN.setVisible(false);
        jLHDisk.setVisible(false);
        jTHDisk.setVisible(false);
        jLPSpeed.setVisible(false);
        jTPSpeed.setVisible(false);
        jLMReq.setVisible(false);
        jTMReq.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPOptions = new javax.swing.JPanel();
        jBBooks = new javax.swing.JButton();
        jBSoftware = new javax.swing.JButton();
        jPGroups = new javax.swing.JPanel();
        jLName = new javax.swing.JLabel();
        jTName = new javax.swing.JTextField();
        jLID = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jLPHouse = new javax.swing.JLabel();
        jTPHouse = new javax.swing.JTextField();
        jLPYear = new javax.swing.JLabel();
        jTPYear = new javax.swing.JTextField();
        jTCost = new javax.swing.JTextField();
        jLCost = new javax.swing.JLabel();
        jTAuthor = new javax.swing.JTextField();
        jLAuthor = new javax.swing.JLabel();
        jLNPages = new javax.swing.JLabel();
        jTNPages = new javax.swing.JTextField();
        jLabelNumberOfPages = new javax.swing.JLabel();
        jTISBN = new javax.swing.JTextField();
        jLISBN = new javax.swing.JLabel();
        jLHDisk = new javax.swing.JLabel();
        jTHDisk = new javax.swing.JTextField();
        jLPSpeed = new javax.swing.JLabel();
        jTPSpeed = new javax.swing.JTextField();
        jLMReq = new javax.swing.JLabel();
        jTMReq = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListBooks = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSoftware = new javax.swing.JList();
        jButtonBookOrder = new javax.swing.JButton();
        jButtonSoftwareOrder = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListOrder = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTSubTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTVAT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTTotal = new javax.swing.JTextField();
        jBSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPOptions.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPTIONS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jBBooks.setText("Books");
        jBBooks.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jBBooks.setBorderPainted(false);
        jBBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBooksMouseClicked(evt);
            }
        });
        jBBooks.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jBBooksComponentShown(evt);
            }
        });

        jBSoftware.setText("Software");
        jBSoftware.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jBSoftware.setBorderPainted(false);
        jBSoftware.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSoftwareMouseClicked(evt);
            }
        });
        jBSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSoftwareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOptionsLayout = new javax.swing.GroupLayout(jPOptions);
        jPOptions.setLayout(jPOptionsLayout);
        jPOptionsLayout.setHorizontalGroup(
            jPOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBBooks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
            .addComponent(jBSoftware, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPOptionsLayout.setVerticalGroup(
            jPOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPGroups.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GROUPS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPGroups.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPGroupsComponentHidden(evt);
            }
        });
        jPGroups.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPGroupsAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLName.setText("Name:");

        jTName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNameActionPerformed(evt);
            }
        });

        jLID.setText("ID:");

        jTID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIDActionPerformed(evt);
            }
        });

        jLPHouse.setText("Publishing House:");

        jTPHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPHouseActionPerformed(evt);
            }
        });

        jLPYear.setText("Publishing Year:");

        jTPYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPYearActionPerformed(evt);
            }
        });

        jTCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCostActionPerformed(evt);
            }
        });

        jLCost.setText("Cost:");

        jTAuthor.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                test(evt);
            }
        });

        jLAuthor.setText("Author:");

        jLNPages.setText("Number of Pages: ");

        jTNPages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNPagesActionPerformed(evt);
            }
        });

        jTISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTISBNActionPerformed(evt);
            }
        });

        jLISBN.setText("ISBN:");

        jLHDisk.setText("Hard Disk:");

        jTHDisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTHDiskActionPerformed(evt);
            }
        });

        jLPSpeed.setText("Processor Speed:");

        jTPSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPSpeedActionPerformed(evt);
            }
        });

        jLMReq.setText("Minimum Requirements:");

        jTMReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMReqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPGroupsLayout = new javax.swing.GroupLayout(jPGroups);
        jPGroups.setLayout(jPGroupsLayout);
        jPGroupsLayout.setHorizontalGroup(
            jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGroupsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTName))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTID))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLPHouse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTPHouse))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLPYear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTPYear))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTCost))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLAuthor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTAuthor))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLNPages)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTNPages))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLabelNumberOfPages)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLISBN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTISBN))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLHDisk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTHDisk))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLPSpeed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTPSpeed))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLMReq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTMReq)))
                .addGap(18, 18, 18))
        );
        jPGroupsLayout.setVerticalGroup(
            jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGroupsLayout.createSequentialGroup()
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLID)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLName)
                    .addComponent(jTName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPHouse)
                    .addComponent(jTPHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPYear)
                    .addComponent(jTPYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCost)
                    .addComponent(jTCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAuthor)
                    .addComponent(jTAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNPages)
                    .addComponent(jTNPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLISBN)
                    .addComponent(jTISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLHDisk)
                    .addComponent(jTHDisk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPSpeed)
                    .addComponent(jTPSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMReq)
                    .addComponent(jTMReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNumberOfPages))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OTHERS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jScrollPane1.setViewportView(jListBooks);

        jListSoftware.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListSoftware);

        jButtonBookOrder.setText("Order Book");
        jButtonBookOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookOrderActionPerformed(evt);
            }
        });

        jButtonSoftwareOrder.setText("Order Software");
        jButtonSoftwareOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSoftwareOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButtonBookOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSoftwareOrder)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBookOrder)
                    .addComponent(jButtonSoftwareOrder))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ORDER", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jListOrder.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListOrderValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListOrder);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOTAL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Subtotal");

        jLabel2.setText("VAT");

        jLabel3.setText("TOTAL");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTVAT, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jTSubTotal)
                    .addComponent(jTTotal))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTVAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jBSubmit.setText("Submit Book");
        jBSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSubmitMouseClicked(evt);
            }
        });
        jBSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPGroups, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jBSubmit)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSoftwareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSoftwareActionPerformed

    private void jTNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNameActionPerformed

    private void jTIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIDActionPerformed

    private void jTPHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPHouseActionPerformed

    private void jTPYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPYearActionPerformed

    private void jTCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCostActionPerformed

    private void jBBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBooksMouseClicked
        // TODO add your handling code here:
        jPGroups.setVisible(true);
        jBSubmit.setText("  Submit Book  ");    
        jBSubmit.setVisible(true);
        jLID.setVisible(true);
        jTID.setVisible(true);
        jLName.setVisible(true);
        jTName.setVisible(true);
        jLPHouse.setVisible(true);
        jTPHouse.setVisible(true);
        jLPYear.setVisible(true);
        jTPYear.setVisible(true);
        jLCost.setVisible(true);
        jTCost.setVisible(true);
        jLAuthor.setVisible(true);
        jTAuthor.setVisible(true);
        jLNPages.setVisible(true);
        jTNPages.setVisible(true);
        jLISBN.setVisible(true);
        jTISBN.setVisible(true);
        jLHDisk.setVisible(false);
        jTHDisk.setVisible(false);
        jLPSpeed.setVisible(false);
        jTPSpeed.setVisible(false);
        jLMReq.setVisible(false);
        jTMReq.setVisible(false);
        
        
        Book b1 = new Book(1,"Microsoft Office",99.99,2014,"Microsoft","Eliazer Raizel", "123123DEASD123", 365);
        
        
        
        
    }//GEN-LAST:event_jBBooksMouseClicked

    private void jBSoftwareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSoftwareMouseClicked

        // TODO add your handling code here:
        jPGroups.setVisible(true);
        jBSubmit.setText("Submit Software");
        
        
        jBSubmit.setVisible(true);
        
       
        jLAuthor.setVisible(false);
        jTAuthor.setVisible(false);
        jLNPages.setVisible(false);
        jTNPages.setVisible(false);
        jLISBN.setVisible(false);
        jTISBN.setVisible(false);
        jLID.setVisible(true);
        jTID.setVisible(true);
        jLName.setVisible(true);
        jTName.setVisible(true);
        jLPHouse.setVisible(true);
        jTPHouse.setVisible(true);
        jLPYear.setVisible(true);
        jTPYear.setVisible(true);
        jLCost.setVisible(true);
        jTCost.setVisible(true);
        jLHDisk.setVisible(true);
        jTHDisk.setVisible(true);
        jLPSpeed.setVisible(true);
        jTPSpeed.setVisible(true);
        jLMReq.setVisible(true);
        jTMReq.setVisible(true);
        //Software s1 = new Software(1,"Microsoft Office",99.99,2014,"Microsoft",500, 2.2, "Windows 7");
    }//GEN-LAST:event_jBSoftwareMouseClicked

    private void jPGroupsComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPGroupsComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jPGroupsComponentHidden

    private void jTNPagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNPagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNPagesActionPerformed

    private void jTISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTISBNActionPerformed

    private void jBBooksComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jBBooksComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBooksComponentShown

    private void jBSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSubmitMouseClicked
        //Book b1 = new Book(001,"Microsoft Office",99.99,2014,"Microsoft","Eliazer Raizel", "123123DEASD123", 365);
        
            if (evt.getSource() == jBSubmit && jBSubmit.getText().contentEquals("  Submit Book  ")){
            
                try{
                int pID = Integer.parseInt(jTID.getText());
                String pName = jTName.getText();
                String pPubHouse = jTPHouse.getText();
                int pYearPub = Integer.parseInt(jTPYear.getText());
                double pCost = Double.parseDouble(jTCost.getText());
                String bAuthor = jTAuthor.getText();
                int bNumberPages = Integer.parseInt(jTNPages.getText());
                String bISBN = jTISBN.getText();

                JOptionPane.showMessageDialog(null, "Book Added!");
                bookList[currentBook] = new Book(pID, pName, pCost, pYearPub, pPubHouse, 
                        bAuthor, bISBN, bNumberPages);
                
                dlmBook.addElement("Book "+(currentBook+1)+": "+bookList[currentBook].getProductName());        
                jListBooks.setModel(dlmBook);
                currentBook++;
                }catch(IllegalArgumentException e){
                    JOptionPane.showMessageDialog(null, "Error there is an empty"
                            + " field, please complete all fields before clicking submit");
                }
        } else {
                
                try{
                    int pID = Integer.parseInt(jTID.getText());
                    String pName = jTName.getText();
                    String pPubHouse = jTPHouse.getText();
                    int pYearPub = Integer.parseInt(jTPYear.getText());
                    double pCost = Double.parseDouble(jTCost.getText());
                    int sHardDisk = Integer.parseInt(jTHDisk.getText());
                    double sProcSpeed = Double.parseDouble(jTPSpeed.getText());
                    String sMinRequirements = jTMReq.getText();
                    
                    softwareList[currentSoftware] = new Software(pID, pName, 
                            pCost, pYearPub, pPubHouse, sHardDisk, sProcSpeed, sMinRequirements);        
                    dlmSoftware.addElement("Book "+(currentSoftware+1)+": "+softwareList[currentSoftware].getProductName());        
                    jListSoftware.setModel(dlmSoftware);
                    currentSoftware++;
                }
                catch(IllegalArgumentException e ){
                    JOptionPane.showMessageDialog(null, "Error there is an empty"
                            + " field, please complete all fields before clicking submit");
                    
                
                
                }
            JOptionPane.showMessageDialog(null, "Software Added!");
           
            
            }
        
        
        
        
        
        
    }//GEN-LAST:event_jBSubmitMouseClicked

    private void jPGroupsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPGroupsAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPGroupsAncestorAdded

    private void test(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_test
        // TODO add your handling code here:
    }//GEN-LAST:event_test

    private void jTHDiskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTHDiskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTHDiskActionPerformed

    private void jTPSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPSpeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPSpeedActionPerformed

    private void jTMReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMReqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMReqActionPerformed

    private void jBSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSubmitActionPerformed
                
    }//GEN-LAST:event_jBSubmitActionPerformed

    private void jButtonBookOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookOrderActionPerformed
        dlmOrder.addElement(jListBooks.getSelectedValue());        
        jListOrder.setModel(dlmOrder);
    }//GEN-LAST:event_jButtonBookOrderActionPerformed

    private void jButtonSoftwareOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSoftwareOrderActionPerformed
        dlmOrder.addElement(jListSoftware.getSelectedValue());        
        jListOrder.setModel(dlmOrder);
    }//GEN-LAST:event_jButtonSoftwareOrderActionPerformed

    private void jListOrderValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListOrderValueChanged
        jTSubTotal.Integer.parseInt(setText());
    }//GEN-LAST:event_jListOrderValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBooks;
    private javax.swing.JButton jBSoftware;
    private javax.swing.JButton jBSubmit;
    private javax.swing.JButton jButtonBookOrder;
    private javax.swing.JButton jButtonSoftwareOrder;
    private javax.swing.JLabel jLAuthor;
    private javax.swing.JLabel jLCost;
    private javax.swing.JLabel jLHDisk;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLISBN;
    private javax.swing.JLabel jLMReq;
    private javax.swing.JLabel jLNPages;
    private javax.swing.JLabel jLName;
    private javax.swing.JLabel jLPHouse;
    private javax.swing.JLabel jLPSpeed;
    private javax.swing.JLabel jLPYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNumberOfPages;
    private javax.swing.JList jListBooks;
    private javax.swing.JList jListOrder;
    private javax.swing.JList jListSoftware;
    private javax.swing.JPanel jPGroups;
    private javax.swing.JPanel jPOptions;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTAuthor;
    private javax.swing.JTextField jTCost;
    private javax.swing.JTextField jTHDisk;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTISBN;
    private javax.swing.JTextField jTMReq;
    private javax.swing.JTextField jTNPages;
    private javax.swing.JTextField jTName;
    private javax.swing.JTextField jTPHouse;
    private javax.swing.JTextField jTPSpeed;
    private javax.swing.JTextField jTPYear;
    private javax.swing.JTextField jTSubTotal;
    private javax.swing.JTextField jTTotal;
    private javax.swing.JTextField jTVAT;
    // End of variables declaration//GEN-END:variables
}
class Products{
    
    // Product Constructors
    
    private int pID;
    private String pName;
    private double pCost;
    private int pYearPub;
    private String pPubHouse;
    
    public Products(int pID, String pName, double pCost, int pYearPub, 
            String pPubHouse){
        
        this.pID = pID;
        this.pName = pName;
        this.pCost = pCost;
        this.pYearPub = pYearPub;
        this.pPubHouse = pPubHouse;
}    
    // Products Setters
    public void setProductID(int pID){
        this.pID=pID;   
    }
    public void setProductName(String pName){
        this.pName=pName;
    }
    public void setProductCost(double pCost){
        this.pCost=pCost;
    }
    public void setProductYearPublication(int pYearPub){
        this.pYearPub=pYearPub;
    }
    public void setProductPublicationHouse(String pPubHouse){
        this.pPubHouse=pPubHouse;
    }
    
    // Products Getters
    public int getProductID(){
        return pID;   
    }
    public String getProductName(){
        return pName;
    }
    public double getProductCost(){
        return pCost;
    }
    public int getProductYearPublication(){
        return pYearPub;
    }
    public String getProductPublicationHouse(){
        return pPubHouse;
    }
    
    




}
