package Amazon;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Interface extends javax.swing.JFrame {
    JList list;
    int bookId = 1;
    int softwareId = 1;
    int clientId = 1;
    int currentBook = 0;
    int currentSoftware = 0;
    int currentOrder = 0;
    Book[] bookList;
    Software[] softwareList;
    Order[] orderList;
    private static boolean conditionsCheck = true;
    
    double subTotalB = 0;
    double subTotalS = 0;
    double vat = 0;
    double total = 0;
    DefaultListModel dlmBook = new DefaultListModel();
    DefaultListModel dlmSoftware = new DefaultListModel();
    DefaultListModel dlmOrder = new DefaultListModel();
    DefaultListModel dlmCost = new DefaultListModel();
    
    /**
     * Creates new form Interface
     */
    
    public Interface() {
        
        this.bookList = new Book [100];
        this.softwareList = new Software [100];
        this.orderList = new Order [100];
        
        
        initComponents();
        
        //Products p1 = new Products(1,"Microsoft Office",99.99,2014,"Microsoft");
        //Book b1 = new Book(1,"Microsoft Office",99.99,2014,"Microsoft","Eliazer Raizel", "123123DEASD123", 365);
        //Software s1 = new Software(1,"Microsoft Office",99.99,2014,"Microsoft",500, 2.2, "Windows 7");
        //Button:
        jBSubmit.setVisible(false);
        //Product:
        jLID.setVisible(false);
        jTID.setVisible(false);
        jLName.setVisible(false);
        jTName.setVisible(false);
        jLPHouse.setVisible(false);
        jTPHouse.setVisible(false);
        jLPYear.setVisible(false);
        jTPYear.setVisible(false);
        jLCost.setVisible(false);
        jTCost.setVisible(false);
        //Book:
        jLAuthor.setVisible(false);
        jTAuthor.setVisible(false);
        jLNPages.setVisible(false);
        jTNPages.setVisible(false);
        jLISBN.setVisible(false);
        jTISBN.setVisible(false);
        //Software:
        jLHDisk.setVisible(false);
        jTHDisk.setVisible(false);
        jLPSpeed.setVisible(false);
        jTPSpeed.setVisible(false);
        jLMReq.setVisible(false);
        jTMReq.setVisible(false);
        //Client:
        jLOID.setVisible(false);
        jTOID.setVisible(false);
        jLClientName.setVisible(false);
        jTClientName.setVisible(false);
        jLAddress.setVisible(false);
        jTAddress.setVisible(false);
        jLPhoneNumber.setVisible(false);
        jTPhoneNumber.setVisible(false);
        jLEmail.setVisible(false);
        jTEmail.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPOptions = new javax.swing.JPanel();
        jBBooks = new javax.swing.JButton();
        jBSoftware = new javax.swing.JButton();
        jBClient = new javax.swing.JButton();
        jBOrders = new javax.swing.JButton();
        jPGroups = new javax.swing.JPanel();
        jLName = new javax.swing.JLabel();
        jTName = new javax.swing.JTextField();
        jLID = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jLPHouse = new javax.swing.JLabel();
        jTPHouse = new javax.swing.JTextField();
        jLPYear = new javax.swing.JLabel();
        jTPYear = new javax.swing.JTextField();
        jTCost = new javax.swing.JTextField();
        jLCost = new javax.swing.JLabel();
        jTAuthor = new javax.swing.JTextField();
        jLAuthor = new javax.swing.JLabel();
        jLNPages = new javax.swing.JLabel();
        jTNPages = new javax.swing.JTextField();
        jLabelNumberOfPages = new javax.swing.JLabel();
        jTISBN = new javax.swing.JTextField();
        jLISBN = new javax.swing.JLabel();
        jLHDisk = new javax.swing.JLabel();
        jTHDisk = new javax.swing.JTextField();
        jLPSpeed = new javax.swing.JLabel();
        jTPSpeed = new javax.swing.JTextField();
        jLMReq = new javax.swing.JLabel();
        jTMReq = new javax.swing.JTextField();
        jLOID = new javax.swing.JLabel();
        jTOID = new javax.swing.JTextField();
        jLClientName = new javax.swing.JLabel();
        jTClientName = new javax.swing.JTextField();
        jLAddress = new javax.swing.JLabel();
        jTAddress = new javax.swing.JTextField();
        jLPhoneNumber = new javax.swing.JLabel();
        jTPhoneNumber = new javax.swing.JTextField();
        jLEmail = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableOrders = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListBooks = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSoftware = new javax.swing.JList();
        jButtonBookOrder = new javax.swing.JButton();
        jButtonSoftwareOrder = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListOrder = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLCostumer = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTSubTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTVAT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTTotal = new javax.swing.JTextField();
        jBSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPOptions.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPTIONS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jBBooks.setText("Books");
        jBBooks.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jBBooks.setBorderPainted(false);
        jBBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBooksMouseClicked(evt);
            }
        });
        jBBooks.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jBBooksComponentShown(evt);
            }
        });
        jBBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBooksActionPerformed(evt);
            }
        });

        jBSoftware.setText("Software");
        jBSoftware.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jBSoftware.setBorderPainted(false);
        jBSoftware.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSoftwareMouseClicked(evt);
            }
        });
        jBSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSoftwareActionPerformed(evt);
            }
        });

        jBClient.setText("Client");
        jBClient.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jBClient.setBorderPainted(false);
        jBClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBClientMouseClicked(evt);
            }
        });
        jBClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClientActionPerformed(evt);
            }
        });

        jBOrders.setText("Orders");
        jBOrders.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jBOrders.setBorderPainted(false);
        jBOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBOrdersMouseClicked(evt);
            }
        });
        jBOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOptionsLayout = new javax.swing.GroupLayout(jPOptions);
        jPOptions.setLayout(jPOptionsLayout);
        jPOptionsLayout.setHorizontalGroup(
            jPOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBBooks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
            .addComponent(jBSoftware, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPOptionsLayout.setVerticalGroup(
            jPOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBClient, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPGroups.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADD NEW CLIENTS / PRODUCTS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPGroups.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPGroupsComponentHidden(evt);
            }
        });
        jPGroups.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPGroupsAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLName.setText("Name:");

        jTName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNameActionPerformed(evt);
            }
        });

        jLID.setText("ID:");

        jTID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIDActionPerformed(evt);
            }
        });

        jLPHouse.setText("Publishing House:");

        jTPHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPHouseActionPerformed(evt);
            }
        });

        jLPYear.setText("Publishing Year:");

        jTPYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPYearActionPerformed(evt);
            }
        });

        jTCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCostActionPerformed(evt);
            }
        });

        jLCost.setText("Cost:");

        jTAuthor.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                test(evt);
            }
        });

        jLAuthor.setText("Author:");

        jLNPages.setText("Number of Pages: ");

        jTNPages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNPagesActionPerformed(evt);
            }
        });

        jTISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTISBNActionPerformed(evt);
            }
        });

        jLISBN.setText("ISBN:");

        jLHDisk.setText("Hard Disk:");

        jTHDisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTHDiskActionPerformed(evt);
            }
        });

        jLPSpeed.setText("Processor Speed:");

        jTPSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPSpeedActionPerformed(evt);
            }
        });

        jLMReq.setText("Minimum Requirements:");

        jTMReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMReqActionPerformed(evt);
            }
        });

        jLOID.setText("OID:");

        jTOID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTOIDActionPerformed(evt);
            }
        });

        jLClientName.setText("Client Name:");

        jTClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTClientNameActionPerformed(evt);
            }
        });

        jLAddress.setText("Address:");

        jTAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTAddressActionPerformed(evt);
            }
        });

        jLPhoneNumber.setText("Phone Number:");

        jTPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPhoneNumberActionPerformed(evt);
            }
        });

        jLEmail.setText("Email:");

        jTEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEmailActionPerformed(evt);
            }
        });

        jTableOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTableOrders);

        javax.swing.GroupLayout jPGroupsLayout = new javax.swing.GroupLayout(jPGroups);
        jPGroups.setLayout(jPGroupsLayout);
        jPGroupsLayout.setHorizontalGroup(
            jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGroupsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTAddress))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLOID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTOID, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLClientName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTClientName))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLMReq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTMReq))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLPSpeed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTPSpeed))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLHDisk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTHDisk))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLNPages)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTNPages, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLISBN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTISBN))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPGroupsLayout.createSequentialGroup()
                                .addComponent(jLPhoneNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTEmail))
                            .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPGroupsLayout.createSequentialGroup()
                                    .addComponent(jLPYear)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTPYear, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLCost)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTCost))
                                .addComponent(jLabelNumberOfPages)
                                .addGroup(jPGroupsLayout.createSequentialGroup()
                                    .addComponent(jLPHouse)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTPHouse))
                                .addGroup(jPGroupsLayout.createSequentialGroup()
                                    .addComponent(jLID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTName, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPGroupsLayout.createSequentialGroup()
                        .addComponent(jLAuthor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTAuthor)))
                .addContainerGap())
        );
        jPGroupsLayout.setVerticalGroup(
            jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGroupsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLID)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLName)
                    .addComponent(jTName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPHouse)
                    .addComponent(jTPHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPYear)
                    .addComponent(jTPYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCost)
                    .addComponent(jTCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAuthor)
                    .addComponent(jTAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNPages)
                    .addComponent(jTNPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLISBN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLHDisk)
                    .addComponent(jTHDisk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPSpeed)
                    .addComponent(jTPSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMReq)
                    .addComponent(jTMReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLOID)
                    .addComponent(jTOID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLClientName)
                    .addComponent(jTClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAddress)
                    .addComponent(jTAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPhoneNumber)
                    .addComponent(jTPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEmail)
                    .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNumberOfPages))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INVENTORY", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jScrollPane1.setViewportView(jListBooks);

        jListSoftware.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListSoftware);

        jButtonBookOrder.setText("Order Book");
        jButtonBookOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookOrderActionPerformed(evt);
            }
        });

        jButtonSoftwareOrder.setText("Order Software");
        jButtonSoftwareOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSoftwareOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButtonBookOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(104, 104, 104)
                        .addComponent(jButtonSoftwareOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSoftwareOrder)
                    .addComponent(jButtonBookOrder))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ORDER SUMARY", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jListOrder.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListOrderValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListOrder);

        jButton1.setText("Delete Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Costumer:");

        jLCostumer.setText("No name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLCostumer)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(66, 66, 66))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLCostumer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOTAL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Subtotal");

        jLabel2.setText("VAT - 20%");

        jLabel3.setText("TOTAL");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTVAT)
                    .addComponent(jTTotal)
                    .addComponent(jTSubTotal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTVAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBSubmit.setText("Submit Book");
        jBSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSubmitMouseClicked(evt);
            }
        });
        jBSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jBSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPGroups, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.getAccessibleContext().setAccessibleName("STOCK");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSoftwareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSoftwareActionPerformed

    private void jBBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBooksMouseClicked
        //Set Values:
        jTID.setText(String.valueOf(bookId));
        // Button
        jPGroups.setVisible(true);
        ((javax.swing.border.TitledBorder) jPGroups.getBorder()).setTitle("ADD BOOK");
        jPGroups.repaint();
        jBSubmit.setText("Submit Book");    
        jBSubmit.setVisible(true);
        // Products:
        jLID.setVisible(true);
        jTID.setVisible(true);
        jLName.setVisible(true);
        jTName.setVisible(true);
        jLPHouse.setVisible(true);
        jTPHouse.setVisible(true);
        jLPYear.setVisible(true);
        jTPYear.setVisible(true);
        jLCost.setVisible(true);
        jTCost.setVisible(true);
        //Books:
        jLAuthor.setVisible(true);
        jTAuthor.setVisible(true);
        jLNPages.setVisible(true);
        jTNPages.setVisible(true);
        jLISBN.setVisible(true);
        jTISBN.setVisible(true);
        //Software:
        jLHDisk.setVisible(false);
        jTHDisk.setVisible(false);
        jLPSpeed.setVisible(false);
        jTPSpeed.setVisible(false);
        jLMReq.setVisible(false);
        jTMReq.setVisible(false);
        //Client:
        jLOID.setVisible(false);
        jTOID.setVisible(false);
        jLClientName.setVisible(false);
        jTClientName.setVisible(false);
        jLAddress.setVisible(false);
        jTAddress.setVisible(false);
        jLPhoneNumber.setVisible(false);
        jTPhoneNumber.setVisible(false);
        jLEmail.setVisible(false);
        jTEmail.setVisible(false);
        //Table
        jTableOrders.setVisible(false);
        
        
        //Book b1 = new Book(1,"Microsoft Office",99.99,2014,"Microsoft","Eliazer Raizel", "123123DEASD123", 365);
        
        
        
        
    }//GEN-LAST:event_jBBooksMouseClicked

    private void jBSoftwareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSoftwareMouseClicked

        //Button:
        jTID.setText(String.valueOf(softwareId));
        jPGroups.setVisible(true);
        ((javax.swing.border.TitledBorder) jPGroups.getBorder()).setTitle("ADD SOFTWARE");
        jPGroups.repaint();
        jBSubmit.setText("Submit Software");
        jBSubmit.setVisible(true);  
        //Book:
        jLAuthor.setVisible(false);
        jTAuthor.setVisible(false);
        jLNPages.setVisible(false);
        jTNPages.setVisible(false);
        jLISBN.setVisible(false);
        jTISBN.setVisible(false);
        //Product:
        jLID.setVisible(true);
        jTID.setVisible(true);
        jLName.setVisible(true);
        jTName.setVisible(true);
        jLPHouse.setVisible(true);
        jTPHouse.setVisible(true);
        jLPYear.setVisible(true);
        jTPYear.setVisible(true);
        jLCost.setVisible(true);
        jTCost.setVisible(true);
        //Software:
        jLHDisk.setVisible(true);
        jTHDisk.setVisible(true);
        jLPSpeed.setVisible(true);
        jTPSpeed.setVisible(true);
        jLMReq.setVisible(true);
        jTMReq.setVisible(true);
        //Client:
        jLOID.setVisible(false);
        jTOID.setVisible(false);
        jLClientName.setVisible(false);
        jTClientName.setVisible(false);
        jLAddress.setVisible(false);
        jTAddress.setVisible(false);
        jLPhoneNumber.setVisible(false);
        jTPhoneNumber.setVisible(false);
        jLEmail.setVisible(false);
        jTEmail.setVisible(false);
        //Table
        jTableOrders.setVisible(false);
    }//GEN-LAST:event_jBSoftwareMouseClicked

    private void jBBooksComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jBBooksComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBooksComponentShown

    private void jBSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSubmitMouseClicked
        //Book b1 = new Book(001,"Microsoft Office",99.99,2014,"Microsoft","Eliazer Raizel", "123123DEASD123", 365);
        
            if (evt.getSource() == jBSubmit && jBSubmit.getText().contentEquals("Submit Book")){
            
                try{
                int pID = Integer.parseInt(jTID.getText());
                String pName = jTName.getText();
                String pPubHouse = jTPHouse.getText();
                int pYearPub = Integer.parseInt(jTPYear.getText());
                double pCost = Double.parseDouble(jTCost.getText());
                String bAuthor = jTAuthor.getText();
                int bNumberPages = Integer.parseInt(jTNPages.getText());
                String bISBN = jTISBN.getText();
                bookList[currentBook] = new Book(pID, pName, pCost, pYearPub, pPubHouse, 
                        bAuthor, bISBN, bNumberPages);
                               
                if (conditionsCheck && bAuthor.equals("")){                    
                    bookList[currentBook].setBookAuthor(bAuthor);                    
                }
                else if (conditionsCheck && bNumberPages<=10){
                    bookList[currentBook].setNumberPages(bNumberPages,bNumberPages); 
                }
                else{
                    
                    dlmBook.addElement("Book "+(currentBook+1)+": "+
                        bookList[currentBook].getProductName());
                    jListBooks.setModel(dlmBook);
                    currentBook++;
                    bookId++;
                    jTID.setText(String.valueOf(bookId));
                
                }
                

                }catch(IllegalArgumentException e){
                    JOptionPane.showMessageDialog(null, "Error there is an empty"
                            + " field, please complete all fields before clicking submit");
                }
        } 
            if(evt.getSource() == jBSubmit && jBSubmit.getText().contentEquals("Submit Software")) {
                
                try{
                    int pID = Integer.parseInt(jTID.getText());
                    String pName = jTName.getText();
                    String pPubHouse = jTPHouse.getText();
                    int pYearPub = Integer.parseInt(jTPYear.getText());
                    double pCost = Double.parseDouble(jTCost.getText());
                    int sHardDisk = Integer.parseInt(jTHDisk.getText());
                    double sProcSpeed = Double.parseDouble(jTPSpeed.getText());
                    String sMinRequirements = jTMReq.getText();
                    softwareList[currentSoftware] = new Software(pID, pName, 
                            pCost, pYearPub, pPubHouse, sHardDisk, sProcSpeed, sMinRequirements);        
                    dlmSoftware.addElement("Soft "+(currentSoftware+1)+": "+
                            softwareList[currentSoftware].getProductName());
                    jListSoftware.setModel(dlmSoftware);
                    currentSoftware++;
                    softwareId++;
                    jTID.setText(String.valueOf(softwareId));
                }catch(IllegalArgumentException e ){
            }
        }
        if(evt.getSource() == jBSubmit && jBSubmit.getText().contentEquals("Add Client")) {
             
            try{
                int oID = Integer.parseInt(jTOID.getText());
                String cName = jTClientName.getText();
                String cAddress = jTAddress.getText();
                int cPhoneNumber = Integer.parseInt(jTPhoneNumber.getText());
                String cEmail = jTEmail.getText();
                orderList[currentOrder] = new Order(oID, cName, cAddress, cPhoneNumber, cEmail);               
                jLCostumer.setText(orderList[currentOrder].getClientName());                        
                currentOrder++;
                clientId++;
                jTOID.setText(String.valueOf(clientId));
                }catch(IllegalArgumentException e){
                    
                }
        }
    }//GEN-LAST:event_jBSubmitMouseClicked

    private void jBSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSubmitActionPerformed
                
    }//GEN-LAST:event_jBSubmitActionPerformed
    
    private void jButtonBookOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookOrderActionPerformed
      
        dlmOrder.addElement(jListBooks.getSelectedValue());
        jListOrder.setModel(dlmOrder);
        subTotalB = bookList[jListBooks.getSelectedIndex()].getProductCost()+subTotalB;
        //System.out.println(subTotalB+subTotalS);
        jTSubTotal.setText(String.valueOf(subTotalB+subTotalS));
        vat =  ((subTotalB+subTotalS)*0.20);
        total = (subTotalB+subTotalS)+vat;
        jTVAT.setText(String.valueOf(vat));
        jTTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_jButtonBookOrderActionPerformed

    private void jButtonSoftwareOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSoftwareOrderActionPerformed
        
        dlmOrder.addElement(jListSoftware.getSelectedValue());
        jListOrder.setModel(dlmOrder);
        subTotalS = softwareList[jListSoftware.getSelectedIndex()].getProductCost()+subTotalS;
        //System.out.println(subTotalS+subTotalB);
        jTSubTotal.setText(String.valueOf(subTotalS+subTotalB));
        vat =  ((subTotalB+subTotalS)*0.20);
        total = (subTotalB+subTotalS)+vat;
        jTVAT.setText(String.valueOf(vat));
        jTTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_jButtonSoftwareOrderActionPerformed

    private void jListOrderValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListOrderValueChanged
       
        
        
    }//GEN-LAST:event_jListOrderValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String STB = jListOrder.getSelectedValue().toString();
        if (STB.contains("B")){
            //
            subTotalB = (subTotalB - bookList[jListOrder.getSelectedIndex()].getProductCost());
            jTSubTotal.setText(String.valueOf(subTotalB+subTotalS));
            vat =  ((subTotalB+subTotalS)*0.20);
            total = (subTotalB+subTotalS)+vat;
            jTVAT.setText(String.valueOf(vat));
            jTTotal.setText(String.valueOf(total));
            dlmOrder.removeElement(jListOrder.getSelectedValue());
            
        }
        if (STB.contains("S")){
        
            //
            subTotalS = (subTotalS - softwareList[jListOrder.getSelectedIndex()].getProductCost());
            jTSubTotal.setText(String.valueOf(subTotalS+subTotalB));
            vat =  ((subTotalB+subTotalS)*0.20);
            total = (subTotalB+subTotalS)+vat;
            jTVAT.setText(String.valueOf(vat));
            jTTotal.setText(String.valueOf(total));
            dlmOrder.removeElement(jListOrder.getSelectedValue());
        }
            
        //System.out.print("\nSof="+textS);
        //System.out.print("\nSof="+STB);
        
        
        
//        System.out.print("\nSof="+subTotalS);
//        System.out.print("\nBooks="+ subTotalB);
//        System.out.print("\n=====Books========");
//        System.out.print(subTotalB - bookList[jListOrder.getSelectedIndex()].getProductCost());
//        System.out.print("\n=====Software============");
//        System.out.print(subTotalS - softwareList[jListOrder.getSelectedIndex()].getProductCost());
//        
        //try{
        //    subTotalS = subTotalS - bookList[jListOrder.getSelectedIndex()].getProductCost();
        //}catch(Exception e){
        //    
        //}
        ///try{
        //    subTotalB = subTotalB - softwareList[jListOrder.getSelectedIndex()].getProductCost();
        //}catch(Exception e){
        //    
        //}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBClientMouseClicked
        //Button:
        jPGroups.setVisible(true);
        jTOID.setText(String.valueOf(clientId));
        ((javax.swing.border.TitledBorder) jPGroups.getBorder()).setTitle("ADD CLIENT");
        jPGroups.repaint();
        jBSubmit.setText("Add Client");
        jBSubmit.setVisible(true);  
        //Book:
        jLAuthor.setVisible(false);
        jTAuthor.setVisible(false);
        jLNPages.setVisible(false);
        jTNPages.setVisible(false);
        jLISBN.setVisible(false);
        jTISBN.setVisible(false);
        //Product:
        jLID.setVisible(false);
        jTID.setVisible(false);
        jLName.setVisible(false);
        jTName.setVisible(false);
        jLPHouse.setVisible(false);
        jTPHouse.setVisible(false);
        jLPYear.setVisible(false);
        jTPYear.setVisible(false);
        jLCost.setVisible(false);
        jTCost.setVisible(false);
        //Software:
        jLHDisk.setVisible(false);
        jTHDisk.setVisible(false);
        jLPSpeed.setVisible(false);
        jTPSpeed.setVisible(false);
        jLMReq.setVisible(false);
        jTMReq.setVisible(false);
        //Client:
        jLOID.setVisible(true);
        jTOID.setVisible(true);
        jLClientName.setVisible(true);
        jTClientName.setVisible(true);
        jLAddress.setVisible(true);
        jTAddress.setVisible(true);
        jLPhoneNumber.setVisible(true);
        jTPhoneNumber.setVisible(true);
        jLEmail.setVisible(true);
        jTEmail.setVisible(true);
        //Table
        jTableOrders.setVisible(false);
    }//GEN-LAST:event_jBClientMouseClicked

    private void jBClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClientActionPerformed

    }//GEN-LAST:event_jBClientActionPerformed

    private void jBOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBOrdersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBOrdersMouseClicked

    private void jBOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOrdersActionPerformed
        //Button:
        jPGroups.setVisible(true);
        jTOID.setText(String.valueOf(clientId));
        ((javax.swing.border.TitledBorder) jPGroups.getBorder()).setTitle("VIEW ORDERS");
        jPGroups.repaint();
        jBSubmit.setText("Dispach");
        jBSubmit.setVisible(true);  
        //Book:
        jLAuthor.setVisible(false);
        jTAuthor.setVisible(false);
        jLNPages.setVisible(false);
        jTNPages.setVisible(false);
        jLISBN.setVisible(false);
        jTISBN.setVisible(false);
        //Product:
        jLID.setVisible(false);
        jTID.setVisible(false);
        jLName.setVisible(false);
        jTName.setVisible(false);
        jLPHouse.setVisible(false);
        jTPHouse.setVisible(false);
        jLPYear.setVisible(false);
        jTPYear.setVisible(false);
        jLCost.setVisible(false);
        jTCost.setVisible(false);
        //Software:
        jLHDisk.setVisible(false);
        jTHDisk.setVisible(false);
        jLPSpeed.setVisible(false);
        jTPSpeed.setVisible(false);
        jLMReq.setVisible(false);
        jTMReq.setVisible(false);
        //Client:
        jLOID.setVisible(false);
        jTOID.setVisible(false);
        jLClientName.setVisible(false);
        jTClientName.setVisible(false);
        jLAddress.setVisible(false);
        jTAddress.setVisible(false);
        jLPhoneNumber.setVisible(false);
        jTPhoneNumber.setVisible(false);
        jLEmail.setVisible(false);
        jTEmail.setVisible(false);
        //Table
        jTableOrders.setVisible(true);
    }//GEN-LAST:event_jBOrdersActionPerformed

    private void jPGroupsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPGroupsAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPGroupsAncestorAdded

    private void jPGroupsComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPGroupsComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jPGroupsComponentHidden

    private void jTEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEmailActionPerformed

    private void jTPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPhoneNumberActionPerformed

    private void jTAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAddressActionPerformed

    private void jTClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTClientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTClientNameActionPerformed

    private void jTOIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTOIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTOIDActionPerformed

    private void jTMReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMReqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMReqActionPerformed

    private void jTPSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPSpeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPSpeedActionPerformed

    private void jTHDiskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTHDiskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTHDiskActionPerformed

    private void jTISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTISBNActionPerformed

    private void jTNPagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNPagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNPagesActionPerformed

    private void test(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_test
        // TODO add your handling code here:
    }//GEN-LAST:event_test

    private void jTCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCostActionPerformed

    private void jTPYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPYearActionPerformed

    private void jTPHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPHouseActionPerformed

    private void jTIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIDActionPerformed

    private void jTNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNameActionPerformed

    private void jBBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBooksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBooks;
    private javax.swing.JButton jBClient;
    private javax.swing.JButton jBOrders;
    private javax.swing.JButton jBSoftware;
    private javax.swing.JButton jBSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBookOrder;
    private javax.swing.JButton jButtonSoftwareOrder;
    private javax.swing.JLabel jLAddress;
    private javax.swing.JLabel jLAuthor;
    private javax.swing.JLabel jLClientName;
    private javax.swing.JLabel jLCost;
    private javax.swing.JLabel jLCostumer;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLHDisk;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLISBN;
    private javax.swing.JLabel jLMReq;
    private javax.swing.JLabel jLNPages;
    private javax.swing.JLabel jLName;
    private javax.swing.JLabel jLOID;
    private javax.swing.JLabel jLPHouse;
    private javax.swing.JLabel jLPSpeed;
    private javax.swing.JLabel jLPYear;
    private javax.swing.JLabel jLPhoneNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelNumberOfPages;
    private javax.swing.JList jListBooks;
    private javax.swing.JList jListOrder;
    private javax.swing.JList jListSoftware;
    private javax.swing.JPanel jPGroups;
    private javax.swing.JPanel jPOptions;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTAddress;
    private javax.swing.JTextField jTAuthor;
    private javax.swing.JTextField jTClientName;
    private javax.swing.JTextField jTCost;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTHDisk;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTISBN;
    private javax.swing.JTextField jTMReq;
    private javax.swing.JTextField jTNPages;
    private javax.swing.JTextField jTName;
    private javax.swing.JTextField jTOID;
    private javax.swing.JTextField jTPHouse;
    private javax.swing.JTextField jTPSpeed;
    private javax.swing.JTextField jTPYear;
    private javax.swing.JTextField jTPhoneNumber;
    private javax.swing.JTextField jTSubTotal;
    private javax.swing.JTextField jTTotal;
    private javax.swing.JTextField jTVAT;
    private javax.swing.JTable jTableOrders;
    // End of variables declaration//GEN-END:variables
}
class Products{
    
    // Product Constructors
    
    private int pID;
    private String pName;
    private double pCost;
    private int pYearPub;
    private String pPubHouse;
    
    public Products(int pID, String pName, double pCost, int pYearPub, 
            String pPubHouse){
        
        this.pID = pID;
        this.pName = pName;
        this.pCost = pCost;
        this.pYearPub = pYearPub;
        this.pPubHouse = pPubHouse;
}    
    // Products Setters
    public void setProductID(int pID){
        this.pID=pID;      
    }
    public void setProductName(String pName){
        this.pName=pName;
        
    }
    public void setProductCost(double pCost){
        this.pCost=pCost;
       
    }
    public void setProductYearPublication(int pYearPub){
        this.pYearPub=pYearPub;
    }
    public void setProductPublicationHouse(String pPubHouse){
        this.pPubHouse=pPubHouse;
    }
    
    // Products Getters
    public int getProductID(){
        return pID;   
    }
    public String getProductName(){
        return pName;
    }
    public double getProductCost(){
        return pCost;
    }
    public int getProductYearPublication(){
        return pYearPub;
    }
    public String getProductPublicationHouse(){
        return pPubHouse;
    }
    
    




}
